### PR TITLE
Add reaction

### PR DESCRIPTION
**Pull request by liamdawson**
Implements API to add an emoji reaction to an incoming message. Also implements the passing of Slack-provided message data via a proposed change to `Lita` (https://github.com/litaio/lita/pull/164), as required to add a reaction.

- [x] Add functionality
- [x] Add tests (waiting on PR merge)
- [x] Bump gem version dependency for `Lita` (waiting on PR merge)

### CODE REVIEW

**Comment by liamdawson** [comment]
(This addresses #73)

**Comment by liamdawson** [comment]
@jimmycuadra — This should be ready for your perusal now.

**Comment by jimmycuadra** [comment]
Looks good, but leave the gemspec alone, I'll bump the version in a separate commit. If you want to leave the "since" tags in the docs, use 1.8.0 for the version number. Then squash everything down to one commit. Thanks for your work on this!

**Comment by jimmycuadra** [comment]
@liamdawson Do you have time to address my last comment? I'm ready to merge this in afterwards.

**Comment by hollow** [comment]
this would be really nice to have. any ETA on the merge?

**Comment by jimmycuadra** [comment]
I'd probably be okay with merging this if my previous comments are ever addressed, but in general there isn't going to be additional functionality added to the chat service API. I'd recommend using a Slack client for Ruby to do Slack-specific stuff directly from your Lita handlers.

**Comment by liamdawson** [comment]
Hey @hollow I didn't end up finishing this off :disappointed: If you want to pick it up and open a new merge, feel free! There wasn't much left, but I'd have to reinstall a ruby dev environment and rebuild a bot and start a slack team etc. to finish it off.

**Comment by jimmycuadra** [comment]
In that case, I'll save anyone the trouble: we're not merging additional Slack-specific features into the adapter. The idea is to allow Lita to does what it does with Slack as the chat service, and the user should never interact with the adapter outside of configuration.

**Pull request closed without merging**
